### ISSUE TITLE
Unused repositories?

### ISSUE THREAD

**Issue by Rudloff** [hypeapps/episodie#23]
Hello,

I am packaging you app for [F-Droid](https://f-droid.org/).
We had to patch it to remove some untrusted Maven repositories: https://gitlab.com/fdroid/fdroiddata/blob/cdeed9c43adabcd48674e31d5d5f20ae297ef49d/metadata/pl.hypeapp.episodie/repositories.patch
The app seems to build correctly without them.

What are they used for? If they are not used, would it be possible to remove them?

**Comment by Bubu** [comment]
`maven { url 'https://dl.google.com/dl/android/maven2/' }` should just be a synonym for `google()` right?

The arturbosch one seems to be needed for `detekt` whatever that is :). But we can easily remove that with sed instead of a patch (patches tend to break way more easily).

Really not sure about the idescout one.

**Comment by hypeapps** [comment]
@Rudloff @Bubu 
Don't worry, just delete them. 
[Artur Bosch(Detekt)](https://github.com/arturbosch/detekt) - is kotlin static code analysis tool for Kotlin.
[IDEScout(SQLScout)](http://www.idescout.com/) - is IDE tool to manage database. I tested it and I forgot to delete the dependency.
